# Generated by Django 5.0.6 on 2024-05-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('science', '科学のこと'), ('dailylife', '日常のこと'), ('music', '音楽のこと')], max_length=50, verbose_name='カテゴリ'),
        ),
    ]
